### ISSUE TITLE
Prize link does not work

### ISSUE THREAD

**Issue by vanshady** [HackDavis/hackdavis.github.io#2]
KPCB challenge

**Comment by sridattb96** [comment]
Fixed!

On Thursday, May 5, 2016, Minwei Xu notifications@github.com wrote:

> KPCB challenge
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/HackDavis/hackdavis.github.io/issues/2

## 

Sridatt Bhamidipati
_University of California, Davis, Class of '17_
tel: 650-533-6987 | email: sbhamidi@ucdavis.edu
