### ISSUE TITLE
Remove navigation's scrollbar for visual enhancement

### ISSUE THREAD

**Issue by KangboLu** [HackDavis/hackdavis.github.io#7]
## The navbar's scrollbar is not hidden because only the overflow-x is hidden or not both x and y
**Before changing the "overflow-x: hidden;" for navbar to "overflow: hidden;"**
![navbar](https://cloud.githubusercontent.com/assets/17485959/20454030/0172742e-adea-11e6-9749-e77720fbf755.png)

**After changing the "overflow-x: hidden;" for navbar to "overflow: hidden;"**
![afterremove](https://cloud.githubusercontent.com/assets/17485959/20454031/0700a410-adea-11e6-8047-952d18a5319c.png)

**I made a pull request: #6**

**Comment by YangVincent** [comment]
Resolved with https://github.com/HackDavis/hackdavis.github.io/pull/6
